### ISSUE TITLE
What is the status of the project

### ISSUE THREAD

**Issue by ntimo** [TS3Tools/TS3Monitor#1]
Hi there,

I wanted to ask you what the status of the project is :) I would like to use your script on my Server.

Thank you,
Timo

**Comment by Sebbo94BY** [comment]
It's in progress. :)

First of all, we need to improve some important things in the [TS3UpdateScript](https://github.com/TS3Tools/TS3UpdateScript).

What do you mean with "you want to use the TS3Monitor in your script"? I'm just asking for providing corresponding support. ;)

**Comment by ntimo** [comment]
I actually meant I want to use the Script to monitor my Teamspeak Server on my Server ;)

**Comment by Sebbo94BY** [comment]
Ah, ok. This makes more sense than your first sentence. :D

**Comment by ntimo** [comment]
I think to too :D Sorry for that. But do you maybe have an eta when it will be ready? And will it need root privileges? Because I would won't to use it without root.

**Comment by Sebbo94BY** [comment]
The script requires root privileges yet.

// Edit
And no, there is no ETA yet.

**Comment by Sebbo94BY** [comment]
Just a quick status udpate: The script is already working as expected.

Next, we're going to improve the script by adding multi-language support, cleaning up the developer lines as well as updating the documentation(s).

**Comment by ntimo** [comment]
Sounds really nice, can't wait to test it out :)

**Comment by Sebbo94BY** [comment]
Sorry for the delay. :(

Hopefully, we will release the **TS3Monitor** by end of December 2016.

What we did yet since the last status update:
- Cleaned up the developer lines
- Added documentation
- Added support for TSDNS
- Added cronjob de-/installation
- Added email notifications
- Added support for [TS3UpdateScript](https://github.com/TS3Tools/TS3UpdateScript)

Next, we'll add multi-language support and test everything once again.

**Comment by Sebbo94BY** [comment]
Hey @ntimo,
I'm happy, that I can announce, that we could already release the **TS3Monitor** today. :)

All of our tests were successful and it did, what it should do.

Just grab your copy [of v1.0.0 here](https://github.com/TS3Tools/TS3Monitor/releases/tag/1.0.0) and let us know, what you think about it.

Feel free to report any improvement/recommendation/suggestion, question and bug in a new issue. Thank you!

I'll close this "issue" with this comment.
