### ISSUE TITLE
Wat

### ISSUE THREAD

**Issue by rafaelsgirao** [TS3Tools/TS3Monitor#3]
Why the heck would you post software to github, specifically BASH code, under the GNU Public License, and then add a "licensing system" (if you could call it that?) with ridiculous prices? Asides from all that crap, works neatly with some personal tweaks to support pushbullet and things...

**Comment by Sebbo94BY** [comment]
The software is available for free and published under the GNU Public License due of it's specifications. The "licensing system" is just for these people, who love the tool and want something more or help to show, that they're interested in the tool and there are a lot of people, who are interested in, trust me.

Why are these prices "ridiculous" in your opinion? To high? To low? However: It doesn't matter. The prices are ok. Just an example: You can buy the same piece of software unencoded - like this - at different companies for different prices. The first company may offers it to you for only 1k EUR and the next for 100k EUR. Each company will get their customers, they only need to know how: Certifications, knowledge, good prominence,...

Thanks for your feedback!
